#composing of the docker

#version configuration
version: '3.8'
# The name of the service
services:
  
  # statefull declerations
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongData:/data/db

  #backend declerations
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile

  #Frontend declerations
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile

  #proxy conditions for ports and content defining
  proxy:
    build:
      context: ./nginx
    ports:
      - "8080:80"
      - "3000:3000"
    
#include the volumes used.
volumes:
  mongData: